# This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
# Note: You may assume that at most one additional character can be added to t.

s=input()
t=input()

def additionalLetter(s,t):
    hash = {}
    for letter in s:
        if letter in hash:
            hash[letter] += 1
        else:
            hash[letter] = 1
    
    for letter in t:
        if letter in hash and hash[letter]>0:
            hash[letter] -= 1
        else:
            return letter

    return ' '

print(additionalLetter(s,t))
